"""
sequence_machine.engine
=========================

The orchestration layer that ties ``fast_surf`` and ``deep_surf`` together
into the public :func:`analyze` API:

    1. Clean the raw input into a :class:`~sequence_machine.core.Sequence`.
    2. Run every Fast Surf. These are cheap enough to always run in full.
    3. If any Fast Surf produced a confident, exact match, short-circuit
       and skip Deep Surfs entirely (the whole point of a "fast path").
       Otherwise, dispatch every Deep Surf under a shared time budget.
    4. Score every candidate that came back (exactness first, then an
       Occam's-razor complexity penalty, then a small bonus for
       out-of-bounds predictability), and return a ranked
       :class:`~sequence_machine.core.AnalysisResult`.

This module deliberately knows nothing about *how* any individual surf
works - it only calls ``run_fast_surfs`` / ``run_deep_surfs`` and scores
whatever ``Candidate`` objects come back. New detectors can be added to
``fast_surf.py`` or ``deep_surf.py`` (or an external module using the
``register_fast_surf`` / ``register_deep_surf`` hooks) without touching
this file at all.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from typing import List, Optional, Union

from .core import AnalysisResult, Candidate, CandidateKind, Sequence
from .deep_surf import run_deep_surfs
from .fast_surf import registered_fast_surfs, run_fast_surfs

RawNumber = Union[int, float, str]


# --------------------------------------------------------------------------- #
# Scoring
# --------------------------------------------------------------------------- #


def _score_candidate(candidate: Candidate, sequence: Sequence) -> float:
    """Occam's-razor scoring: exactness dominates, then reward simplicity,
    then reward how far past the observed data the candidate can still be
    evaluated without failing (a lightweight proxy for "generalizes /
    predicts well beyond what we already know").
    """
    exact, max_err = candidate.verify(sequence)
    candidate.exact = exact
    candidate.max_abs_error = max_err

    if not exact:
        # Inexact candidates are only useful as a fallback when nothing
        # exact was found; heavily penalise but keep them ordered sensibly
        # by how close they got and how simple they are.
        return -1_000.0 - max_err * 10 - candidate.complexity * 0.1

    # Exact matches are ranked primarily by simplicity (fewer AST nodes /
    # lower recurrence order / shorter description = more likely to be the
    # "true" generating rule rather than an elaborate coincidence).
    score = 1_000.0 - candidate.complexity * 5.0

    # Small tie-breaking bonus: candidates that can still be evaluated a
    # good distance beyond the given data (i.e. don't immediately divide
    # by zero or hit a domain error) are slightly preferred.
    next_start = sequence.start_index + len(sequence)
    reach = 0
    for offset in range(10):
        try:
            candidate.predict(next_start + offset)
            reach += 1
        except (ZeroDivisionError, ValueError, OverflowError):
            break
    score += reach * 0.1
    return score


def _rank(candidates: List[Candidate], sequence: Sequence) -> List[Candidate]:
    for c in candidates:
        c.score = _score_candidate(c, sequence)
    # Deduplicate candidates that ended up with an identical description
    # (different surfs sometimes rediscover the same rule).
    seen = set()
    unique: List[Candidate] = []
    for c in sorted(candidates, key=lambda c: -c.score):
        if c.description in seen:
            continue
        seen.add(c.description)
        unique.append(c)
    return unique


def _is_confidently_exact(candidate: Optional[Candidate]) -> bool:
    """Whether the best-ranked Fast Surf candidate is trustworthy enough to
    skip Deep Surfs entirely.

    Every non-recurrence Fast Surf already enforces its own redundancy
    requirement internally (see e.g. ``fit_minimal_polynomial``'s
    ``min_redundancy``), so an exact constant/affine/geometric/dictionary/
    polynomial match is trusted immediately - there is no simpler tier of
    search left to consult.

    A ``RECURRENCE``-kind match is treated differently: Berlekamp-Massey
    only ever fits a *homogeneous* recurrence, and a sequence generated by
    a low-order recurrence with a polynomial forcing term (e.g.
    ``a(n) = a(n-1) + n**2``) is mathematically equivalent to a
    substantially higher-order homogeneous one. Fast Surf's answer in that
    case is technically exact but needlessly complex; Deep Surf's
    dedicated non-homogeneous recurrence search exists specifically to
    find the simpler underlying rule, so a bare recurrence match alone
    does not short-circuit it.

    Note this must be evaluated against the *best-ranked* fast candidate,
    not "any" fast candidate - a weaker, coincidentally-simpler alternative
    sitting further down the list should never suppress a legitimate
    Deep Surf pass that could out-simplify the true top pick.
    """
    if candidate is None:
        return False
    return candidate.exact and candidate.kind != CandidateKind.RECURRENCE


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #

@dataclass
class SequenceMachine:
    """A configurable facade over the analysis pipeline.

    Most callers should just use the module-level :func:`analyze`
    convenience function; construct a ``SequenceMachine`` directly when you
    want to reuse the same settings (timeout, prediction horizon, ...)
    across many sequences without repeating keyword arguments.
    """

    deep_surf_timeout: float = 4.0
    top_k: int = 5
    predict_n: int = 5
    enable_oeis: bool = False
    max_deep_workers: Optional[int] = None

    def analyze(
        self,
        raw_values: List[RawNumber],
        start_index: int = 0,
    ) -> AnalysisResult:
        started = time.monotonic()
        sequence = Sequence.from_raw(raw_values, start_index=start_index)

        fast_candidates = run_fast_surfs(sequence)
        surfs_run = list(registered_fast_surfs())

        # Rank the fast candidates first so the short-circuit decision is
        # based on the genuine best pick, not on some weaker alternative
        # further down the list happening to look confident on its own.
        fast_ranked = _rank(fast_candidates, sequence)
        best_fast = fast_ranked[0] if fast_ranked else None

        used_deep_surf = not _is_confidently_exact(best_fast)
        all_candidates = list(fast_candidates)
        if used_deep_surf:
            deep_candidates = run_deep_surfs(
                sequence,
                timeout=self.deep_surf_timeout,
                max_workers=self.max_deep_workers,
                enable_oeis=self.enable_oeis,
            )
            all_candidates.extend(deep_candidates)

        ranked = _rank(all_candidates, sequence)
        elapsed = time.monotonic() - started
        return AnalysisResult(
            sequence=sequence,
            candidates=ranked,
            elapsed_seconds=elapsed,
            surfs_run=surfs_run,
            used_deep_surf=used_deep_surf,
        )


def analyze(
    raw_values: List[RawNumber],
    start_index: int = 0,
    deep_surf_timeout: float = 4.0,
    top_k: int = 5,
    predict_n: int = 5,
    enable_oeis: bool = False,
    max_deep_workers: Optional[int] = None,
) -> AnalysisResult:
    """Discover the closed-form formula, recurrence, or generative rule
    behind ``raw_values``.

    Parameters
    ----------
    raw_values:
        The sequence terms - ints, floats, ``Fraction``s, or numeric
        strings (including ``"1/3"``-style fractions).
    start_index:
        The index associated with ``raw_values[0]`` (0 or 1 are the usual
        conventions).
    deep_surf_timeout:
        Wall-clock seconds allotted to the Deep Surfs *in total* (they run
        concurrently, sharing this one budget). Never consulted if a Fast
        Surf already found a confident, exact match.
    top_k:
        How many ranked candidates ``AnalysisResult.to_dict()`` includes
        by default (the full ranked list is always on ``.candidates``).
    predict_n:
        How many out-of-bounds terms ``AnalysisResult.predictions()``
        returns by default.
    enable_oeis:
        Whether to allow the (network-dependent) OEIS lookup Deep Surf.
        Off by default since it requires outbound internet access.
    max_deep_workers:
        Override the Deep Surf thread pool size; defaults to one worker
        per registered Deep Surf.

    Returns
    -------
    AnalysisResult
        Ranked candidates, with ``.best`` giving the top pick.

    Example
    -------
        >>> result = analyze([1, 1, 2, 3, 5, 8, 13])
        >>> result.best.description
        'a(n) = 1*a(n-1) + 1*a(n-2)   [with a(0)=1, a(1)=1]'
    """
    machine = SequenceMachine(
        deep_surf_timeout=deep_surf_timeout,
        top_k=top_k,
        predict_n=predict_n,
        enable_oeis=enable_oeis,
        max_deep_workers=max_deep_workers,
    )
    return machine.analyze(raw_values, start_index=start_index)
